str="itzcn";
puts str.capitalize;
puts str;
puts str.upcase;
cn="ITZCN";
puts cn.downcase;
itzcn="ItZcN";
puts itzcn.swapcase;
study=" Network to learn the ChuangNei ";
puts study.strip;
puts study.lstrip;
puts study.rstrip;
puts s=study.reverse;
puts s.reverse;
